I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 62, in script
    MB "Do you have the ship ready?"
Exception: Sayer 'MB' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 62, in script
    MB "Do you have the ship ready?"
  File "C:\Users\Briswagg Nation\Documents\Ren'Py\renpy-6.99.12.4-sdk\renpy\ast.py", line 593, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Briswagg Nation\Documents\Ren'Py\renpy-6.99.12.4-sdk\renpy\ast.py", line 509, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'MB' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
GWC Final Project 1.0
